apiVersion: v1
kind: Pod
metadata:
  name: aws-kms-setup
  namespace: kube-system
  labels:
    name: aws-kms-setup
spec:
  containers:
  - name: aws-kms-setup
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: aws_secret_access_key
    - name: AWS_DEFAULT_REGION
      value: "{{.AWSRegion}}"
    - name: OPENSHIFT_INFRA_NAME
      value: "{{.OpenShiftInfraId}}"
    image: public.ecr.aws/aws-cli/aws-cli
    command:
    - "bash"
    args:
    - "/var/src/kms/setup-kms.sh"
    # command:
    # - "sleep"
    # args:
    # - "600"
    resources:
      limits:
        memory: "64Mi"
        cpu: "300m"
    volumeMounts:
    - name: kms-script
      mountPath: /var/src/kms
  volumes:
  - name: kms-script
    configMap:
      name: kms-script
  restartPolicy: OnFailure
  serviceAccountName: kms-setup-sa
